In [9]:
#Ejercicio 1
#Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y
#finalmente muestre la secuencia invertida.

cadena = input("Ingresa una secuencia de caracteres: ")
lista = []

for i in cadena:
    lista.append(i)

lista.reverse()
print("La secuencia queda", lista)


Ingresa una secuencia de caracteres: ff
La secuencia queda ['f', 'f']


In [12]:
#Ejercicio 2
#Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último,
#mostrar el contenido de la lista.
#Por ejemplo, si introducimos hola caracola y adios marieta, debería mostrarse haodleao sc
#amraarcioeltaa.


cad1 = input("Ingresa la primer secuencia: ")
cad2 = input("Ingresa la segunda secuencia: ")

lista = []

if len(cad1) == len(cad2):
    for i in range(len(cad1)):
        lista.append(cad1[i])
        lista.append(cad2[i])
    for c in lista:
        print(c, end = "")
else:
    print("Las cadenas no tienen el mismo largo, inténtalo otra vez")
        

Ingresa la primer secuencia: hola
Ingresa la segunda secuencia: hola
hhoollaa

In [15]:
#Ejercicio 3
#crea un programa que lea un string y guarde en una lista todas las consonantes.

cad = input("Ingresa un texto para obtener las consonantes: ")

lista = []


for i in cad.lower():
    if i not in ("a", "e", "i", "o", "u"):
        lista.append(i)

print("Las cosonantes son: ", lista)



Ingresa un texto para obtener las consonantes: hola
Las cosonantes son:  ['h', 'l']


In [36]:
#Ejercicio 4
#Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.

cadena = input("Ingresa una secuencia de caracteres: ")
lista = []

for i in cadena:
    lista.append(i)

listaInversa = lista.copy()
lista.reverse()
    
if lista == listaInversa:
    print("La secuencia es un palindromo")
else: 
    print("La secuencia NO es un palindromo")

Ingresa una secuencia de caracteres: la osa lava la losa
La secuencia NO es un palindromo


In [50]:
#Ejercicio 5
#Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.

A = []        

for i in range(3):
    A.append([])
    for j in range(3):
        A[i].append(float(input("Introduce el elemento ({},{}) de la Matriz A: ".format(i,j))))

for i in range(3):
    A[i].sort()
    print("El máximo de la fila {} es {}".format(i,A[i][2]))

Introduce el elemento (0,0) de la Matriz A: 4
Introduce el elemento (0,1) de la Matriz A: 5
Introduce el elemento (0,2) de la Matriz A: 1
Introduce el elemento (1,0) de la Matriz A: 6
Introduce el elemento (1,1) de la Matriz A: 88
Introduce el elemento (1,2) de la Matriz A: 9
Introduce el elemento (2,0) de la Matriz A: 1
Introduce el elemento (2,1) de la Matriz A: 55
Introduce el elemento (2,2) de la Matriz A: 2
El máximo de la fila 0 es 5.0
El máximo de la fila 1 es 88.0
El máximo de la fila 2 es 55.0


In [67]:
#Ejercicio 6
#Crea un programa que lea un entero, n, de teclado y construya una matriz de tamaño n × n. Cada posición
#debe contener su orden en la matriz (desde 0 hasta n2 − 1. Por ejemplo, si n es 3, deberá crearse la matriz
#[0, 1, 2]
#[3, 4, 5]
#[6, 7, 8]

num = int(input("Escribe el tamaño de la Matriz A"))
A = []

for i in range(num):
    A.append([])
    for j in range(num):
        A[i].append((num * i) +j) 

for i in range(num):
    print(A[i])



Escribe el tamaño de la Matriz A3
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]


In [65]:
#Ejercicio 7
#Crea una matriz de n × m y asigna los valores manualmente. El programa debe indicar si la suma de cada
#columna es el mismo valor.

num1 = int(input("Escribe el n de la Matriz A: "))
num2 = int(input("Escribe el m de la Matriz A: "))
A = []

for i in range(num1):
    A.append([])
    for j in range(num2):
        A[i].append(float(input("Introduce el elemento ({},{}) de la Matriz A: ".format(i,j))))


listaSuma = []

for i in range(num1):
    suma = 0
    for j in range(num2):
        suma += A[i][j]
    listaSuma.append(suma)

mismaSuma = True
for i in range(len(listaSuma)-1):
    if listaSuma[i] != listaSuma[i+1]:
        mismaSuma = False

print("La suma de las filas {} es igual".format("Si" if mismaSuma else "No"))


Escribe el n de la Matriz A3
Escribe el m de la Matriz A3
Introduce el elemento (0,0) de la Matriz A: 1
Introduce el elemento (0,1) de la Matriz A: 25
Introduce el elemento (0,2) de la Matriz A: 1
Introduce el elemento (1,0) de la Matriz A: 1
Introduce el elemento (1,1) de la Matriz A: 1
Introduce el elemento (1,2) de la Matriz A: 1
Introduce el elemento (2,0) de la Matriz A: 1
Introduce el elemento (2,1) de la Matriz A: 1
Introduce el elemento (2,2) de la Matriz A: 1
La suma de las filas No es igual


In [66]:
#Ejercicio 8
#Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos)
#se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.


num1 = int(input("Escribe el n de la Matriz A: "))
num2 = int(input("Escribe el m de la Matriz A: "))
A = []


for i in range(num1):
    A.append([])
    for j in range(num2):
        A[i].append(float(input("Introduce el elemento ({},{}) de la Matriz A: ".format(i,j))))


identidad = True

if num1 == num2:
    for i in range(num1):
        for j in range(num2):
            if (i == j and A[i][j] != 1) or (i != j and A[i][j] != 0):
                identidad = False

else:
    identidad = False

print("{}Es la Matriz identidad".format("" if identidad else "NO "))


Escribe el n de la Matriz A: 3
Escribe el m de la Matriz A: 3
Introduce el elemento (0,0) de la Matriz A: 1
Introduce el elemento (0,1) de la Matriz A: 0
Introduce el elemento (0,2) de la Matriz A: 0
Introduce el elemento (1,0) de la Matriz A: 0
Introduce el elemento (1,1) de la Matriz A: 1
Introduce el elemento (1,2) de la Matriz A: 0
Introduce el elemento (2,0) de la Matriz A: 0
Introduce el elemento (2,1) de la Matriz A: 0
Introduce el elemento (2,2) de la Matriz A: 1
Es la Matriz identidad


In [86]:
#Ejercicio 9
#Realiza un programa que calcule la matriz transpuesta.


A = [["a","a","a"],["b","b","b"],["c","c","c"]]

T = []
for i in range(len(A[0])):
    T.append([])
    for j in range(len(A)):
        T[i].append(A[j][i])

print("Matriz Original:")
for i in range(len(A)):
    print(A[i])

print("\n Matriz Traspuesta:")
for i in range(len(A)):
    print(T[i])

Matriz Original:
['a', 'a', 'a']
['b', 'b', 'b']
['c', 'c', 'c']

 Matriz Traspuesta:
['a', 'b', 'c']
['a', 'b', 'c']
['a', 'b', 'c']


In [87]:
#Ejercicio 10
#Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con
#numpy.

import numpy as np

num = int(input())
A = np.zeros((num,num))
for i in range(num):
    A[i, i] = 1

print(A)


3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


numpy.ndarray